[project]
name = "dbservice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Andrea Sciortino", email = "andreasciortino2004@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.142.4",
]

[project.scripts]
dbservice = "dbservice:main"

[tool.fastapi]
entrypoint = "main:app"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
